# Generated by Django 3.1.7 on 2023-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix_zabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_start', models.CharField(max_length=200, null=True)),
                ('problem_name', models.CharField(max_length=200, null=True)),
                ('host', models.CharField(max_length=200, null=True)),
                ('severity', models.CharField(max_length=200, null=True)),
                ('problem_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
